// <auto-generated />
using McvFriends.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McvFriends.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211209142603_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("McvFriends.Models.Friend", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "Mary@gmail.com",
                            Mobile = "0922-355822",
                            Name = "Mary"
                        },
                        new
                        {
                            id = 2,
                            Email = "David@gmail.com",
                            Mobile = "0933-123456",
                            Name = "David"
                        },
                        new
                        {
                            id = 3,
                            Email = "Rose@gmail.com",
                            Mobile = "0955-888-163",
                            Name = "Rose"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
